services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic

  app:
    image: joshua122/petclinic:v9
    ports:
      - "8080:8080"
    links:
      - db:db
    environment:
      SPRING_PROFILES_ACTIVE: mysql

